global:
    external_labels:
       monitor: 'hostname'

rule_files:
    - '/pingprom/alert.rules'

scrape_configs:
  - job_name: 'bb'
    scrape_interval: 5m
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - /pingprom/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackboxprober:9115  # Blackbox exporter.
